on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  generate_logo:
    name: generate repo. logo
    runs-on: ubuntu-latest
    steps:
      - name: insall the one and only dependency
        run: pip install pillow
      - name: run the script
        run: python ./resources/logo.py
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master